indentation: 4
excluded:
- Pods
- Pods Internal
- SecureCalendar20/CoreData/EncryptedStore
- SecureCalendar20Tests

disabled_rules:
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - switch_case_alignment
  - weak_delegate

type_name:
  max_length:
    warning: 60

function_parameter_count:
  warning: 10
  error: 15

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
    - to
    - at
    - up
    - vc
    - my

type_body_length:
  warning: 400
  error: 450

file_length:
  warning: 500

line_length:
  warning: 250
  error: 300
  ignores_function_declarations: true
  ignores_comments: true

large_tuple:
  warning: 3
  error: 5

force_cast: 
  error

force_unwrapping:
  error

opt_in_rules:
  - empty_count
  - force_unwrapping
  - force_cast
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_discardable_let
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

unused_optional_binding:
  ignore_optional_try: true

nesting:
    type_level: 2
